In [231]:
import pandas as pd 
df_copy= pd.read_excel('C:\\SENTIMENT DATA.xlsx') 

In [232]:
df_copy['COMMENTS']

0      Effectively measured the impact of X on brandi...
1      Created a list of must-do tasks while negotiat...
2      Reduced errors in handling customer grievances...
3      Is able to comprehend how to follow a complex ...
4      Displays excellent organization skills during ...
                             ...                        
455    Achieved phenomenal growth with number of visi...
456    Has developed a team-oriented approach among a...
457    X is the go-to person to have a fresh look at ...
458    Lacks the ability to understand employee needs...
459    Sets unrealistic expectations leading to over-...
Name: COMMENTS, Length: 460, dtype: object

In [233]:
a="Python"
b="python"
a==b

False

In [234]:
df_copy["COMMENTS"]=df_copy["COMMENTS"].apply(lambda x:" ".join(x.lower() for x in str(x).split()))

In [235]:
df_copy["COMMENTS"]

0      effectively measured the impact of x on brandi...
1      created a list of must-do tasks while negotiat...
2      reduced errors in handling customer grievances...
3      is able to comprehend how to follow a complex ...
4      displays excellent organization skills during ...
                             ...                        
455    achieved phenomenal growth with number of visi...
456    has developed a team-oriented approach among a...
457    x is the go-to person to have a fresh look at ...
458    lacks the ability to understand employee needs...
459    sets unrealistic expectations leading to over-...
Name: COMMENTS, Length: 460, dtype: object

In [236]:
df_copy["COMMENTS"]=df_copy["COMMENTS"].str.replace('[^\w\s]','')

In [237]:
df_copy["COMMENTS"]

0      effectively measured the impact of x on brandi...
1      created a list of mustdo tasks while negotiati...
2      reduced errors in handling customer grievances...
3      is able to comprehend how to follow a complex ...
4      displays excellent organization skills during ...
                             ...                        
455    achieved phenomenal growth with number of visi...
456    has developed a teamoriented approach among al...
457    x is the goto person to have a fresh look at a...
458    lacks the ability to understand employee needs...
459    sets unrealistic expectations leading to overc...
Name: COMMENTS, Length: 460, dtype: object

In [238]:
df_copy["COMMENTS"]=df_copy["COMMENTS"].str.replace('\d+','')

In [239]:
from nltk.corpus import stopwords
stop=stopwords.words('english')

In [240]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [241]:
stop.append('unlock')

In [242]:
stop

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [243]:
df_copy['COMMENTS']=df_copy['COMMENTS'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

In [244]:
df_copy['COMMENTS'].head()

0    effectively measured impact x branding company...
1    created list mustdo tasks negotiating customer...
2    reduced errors handling customer grievances im...
3    able comprehend follow complex set instruction...
4    displays excellent organization skills tasks h...
Name: COMMENTS, dtype: object

In [245]:
from nltk.stem import PorterStemmer
st=PorterStemmer()
df_copy['COMMENTS'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))

0      effect measur impact x brand compani introduc ...
1      creat list mustdo task negoti custom increas p...
2      reduc error handl custom grievanc implement ef...
3      abl comprehend follow complex set instruct eve...
4      display excel organ skill task hesh undertak h...
                             ...                        
455    achiev phenomen growth number visitor websit s...
456    develop teamori approach among employe highli ...
457    x goto person fresh look long stand challeng w...
458    lack abil understand employe need take time av...
459    set unrealist expect lead overcommit underdeli...
Name: COMMENTS, Length: 460, dtype: object

In [246]:
from sklearn.feature_extraction.text import CountVectorizer

In [247]:
cv=CountVectorizer()
X = cv.fit_transform(df_copy['COMMENTS']).toarray()


In [248]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [249]:
X.shape

(460, 1441)

In [250]:
import numpy
numpy.savetxt("foo.csv", X, delimiter=",")

In [251]:
a = cv.get_feature_names()

In [252]:
a

['abandons',
 'abilities',
 'ability',
 'able',
 'abreast',
 'absolutely',
 'abysmal',
 'accept',
 'accepting',
 'according',
 'accordingly',
 'account',
 'accountability',
 'accountable',
 'accounting',
 'accuracy',
 'accurate',
 'accused',
 'achieve',
 'achieved',
 'achievement',
 'achiever',
 'achieves',
 'achieving',
 'acknowledges',
 'across',
 'action',
 'actionable',
 'actively',
 'activities',
 'activity',
 'actual',
 'actually',
 'acumen',
 'adapt',
 'adapts',
 'address',
 'addressing',
 'adhering',
 'adopts',
 'advanced',
 'advancement',
 'advancements',
 'advances',
 'advertising',
 'advice',
 'affect',
 'affecting',
 'aggressive',
 'aggressively',
 'agile',
 'ahead',
 'align',
 'aligns',
 'allocate',
 'allocation',
 'allotted',
 'also',
 'alternative',
 'always',
 'ambiguous',
 'ambitious',
 'among',
 'amount',
 'analyses',
 'analysis',
 'analytical',
 'analytics',
 'analyze',
 'analyzes',
 'analyzing',
 'angryfrustratedrude',
 'annual',
 'anonymous',
 'answers',
 'anticipa

In [253]:
df=pd.DataFrame(a)
df.to_csv('foo1.csv',index=False)

In [254]:
y = df_copy['POLARITY']
y

0      1
1      1
2      1
3      1
4      1
      ..
455    1
456    1
457    1
458    0
459    0
Name: POLARITY, Length: 460, dtype: int64

In [255]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=0)

In [256]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [257]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [258]:
y_train

299    1
96     0
411    0
160    0
142    0
      ..
323    1
192    1
117    1
47     1
172    0
Name: POLARITY, Length: 368, dtype: int64

In [259]:
y_test

329    1
153    0
135    0
78     0
452    0
      ..
301    0
55     0
208    1
205    1
107    1
Name: POLARITY, Length: 92, dtype: int64

In [260]:
X_train.shape

(368, 1441)

In [261]:
X_test.shape

(92, 1441)

In [262]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [263]:
def show_most_informative_features(vectorizer, clf, n=25):
    d = {}
    a=0
    feature_names = vectorizer.get_feature_names()
    coefs_with_fns = sorted(zip(clf.coef_[0], feature_names))
    top = zip(coefs_with_fns[:n], coefs_with_fns[:-(n + 1):-1])
    print("\t\t\tNegative\t\t\t\t\t\tPositive")
    print("________________________________________________________________________________________________")
    for (coef_1, fn_1), (coef_2, fn_2) in top:
        print("\t%.4f\t%-15s\t\t\t\t%.4f\t%-15s" % (coef_1, fn_1, coef_2, fn_2))
        d[a]=fn_1
        a+=1
    
show_most_informative_features(cv,clf)

			Negative						Positive
________________________________________________________________________________________________
	-0.8190	lacks          				0.7772	customer       
	-0.8163	negotiations   				0.7359	technological  
	-0.7302	take           				0.6808	ability        
	-0.6707	poor           				0.6616	displays       
	-0.6657	leading        				0.6615	mistakes       
	-0.6507	skills         				0.6536	whenever       
	-0.6125	support        				0.6445	handle         
	-0.5997	lack           				0.6207	ensure         
	-0.5969	decisions      				0.6166	policies       
	-0.5957	met            				0.6162	existing       
	-0.5730	analyzing      				0.5974	responsibility 
	-0.5596	activities     				0.5948	highly         
	-0.5530	focuses        				0.5767	effective      
	-0.5438	unrealistic    				0.5664	providing      
	-0.5388	complained     				0.5621	accounting     
	-0.5383	integrity      				0.5571	situations     
	-0.5284	instructions   				0.5566	technical      
	-0.5210	f

In [264]:
y_pred = clf.predict(X_test)

In [265]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1], dtype=int64)

In [266]:
y_test

329    1
153    0
135    0
78     0
452    0
      ..
301    0
55     0
208    1
205    1
107    1
Name: POLARITY, Length: 92, dtype: int64

In [267]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.75      0.76        48
           1       0.73      0.75      0.74        44

    accuracy                           0.75        92
   macro avg       0.75      0.75      0.75        92
weighted avg       0.75      0.75      0.75        92



In [269]:
import pandas as pd 
df_copy= pd.read_excel('C:\\predict_comment.xlsx')

In [272]:
df_copy['COMMENT'] = df_copy['COMMENT'].apply(lambda x: " ".join(x.lower() for x in str(x).split()))
# TOLOWER

df_copy['COMMENT'] = df_copy['COMMENT'].str.replace('[^\w\s]','')
# Remove punctuations

df_copy["COMMENT"]=df_copy["COMMENT"].str.replace('\d+','')
# Remove digits

from nltk.corpus import stopwords
stop = stopwords.words('english')
df_copy['COMMENT'] = df_copy['COMMENT'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df_copy['COMMENT'].head()
# Remove Stop Words

from nltk.stem import PorterStemmer
st = PorterStemmer()
df_copy['COMMENT'].apply(lambda x: " ".join([st.stem(word) for word in x.split()]))
# Stemming

0     littl patienc deal obstacl argu aggress teamma...
1     focu menial task rather produc financi report ...
2     organ project task order import ensur work com...
3     help increas complianc safeti mainten regul pr...
4     hardli pay attent rule regul workplac difficul...
                            ...                        
56    achiev phenomen growth number visitor websit s...
57    develop teamori approach among employe highli ...
58    x goto person fresh look long stand challeng w...
59    lack abil understand employe need take time av...
60    set unrealist expect lead overcommit underdeli...
Name: COMMENT, Length: 61, dtype: object

In [273]:
feature_list = cv.get_feature_names()

In [274]:
vect= CountVectorizer(vocabulary = feature_list)
X = vect.transform(df_copy['COMMENT']).toarray() 

In [275]:
y_pred = clf.predict(X)

In [276]:
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0], dtype=int64)